name: Deploy Artifacts

on:
  workflow_call:
    inputs:
      version:
        required: false
        type: string
        description: Version to author


jobs:
  upload_artifacts:
    name: Deploy Artifacts ${{ matrix.python }}-${{ matrix.arch }}-${{ matrix.platform }}
    runs-on:
      - self-hosted
      - linux
      - repo-release
    environment: release
    strategy:
      matrix:
        python:
          - 3.10.11
          - 3.11.3
        platform:
          - linux-gnu
          - win
          - macos
        arch:
          - aarch64
          - amd64
          - x86_64
          - x86
        exclude:
          - platform: linux-gnu
            arch: amd64
          - platform: linux-gnu
            arch: x86
          - platform: win
            arch: aarch64
          - platform: win
            arch: x86_64
          - platform: macos
            arch: aarch64
          - platform: macos
            arch: amd64
          - platform: macos
            arch: x86
    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v3
      with:
        name: ${{ matrix.python }}-${{ matrix.arch }}-${{ matrix.platform }}.tar.xz
        path: release-artifacts/

    - name: Install `awscli`
      run: |
        pip3 install awscli

    - name: "Deploy Python Build: ${{ matrix.python }}-${{ matrix.arch }}-${{ matrix.platform }}.tar.xz"
      run: |
        aws s3 cp release-artifacts/* s3://salt-project-test-salt-artifacts-release/relenv/${{ inputs.version }}/build/
